apiVersion: v1
kind: Service
metadata:
  name: frontend-demo-svc
  namespace: microservices
spec:
  selector:
    app: frontend-demo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
